### ISSUE TITLE
Add Freedom mode to gameoption.yaml

### ISSUE THREAD

**Issue by BobTheGimp** [B-iggy/HWS-Creative-Scenario#3]
In the next update can you please add "- Freedom" as a valid game mode in the gameoption.yaml under the -MP & - Survival section.
This will enable private test servers running in Freedom mode to use the master config without modification. Not an urgent request.

**Comment by B-iggy** [comment]
I never bothered to even start the Freedom mode in Empyrion.
Are you aware of the commands
"cm" in the console?
Switching between Creative and Survival mode?

Either way, since you are aware of the gameoptions.yaml, why not adding it yourself?
I'm asking cause the default dedicated.yaml file is not what I deliver anyways.
Each player can do it how they like...

But I can add it of course... ¯\_(ツ)_/¯
